---
abstract: 'Conveniently manage the nginx fastcgi cache'
author:
  - 'David Farrell <sillymoos@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.010, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nginx-FastCGI-Cache
version: 0.001
